services:
  app:
    container_name: cryptocurrencies-portefolio
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm run setup && npm run start"

